version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bookstore_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_store:/var/lib/postgresql/data
    restart: unless-stopped

  # importer:
  #  build: ./importer
  #  container_name: books_importer
  #  depends_on:
  #    - postgres
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: password
  #    POSTGRES_HOST: postgres
  #    POSTGRES_PORT: 5432
  #    POSTGRES_DB: bookstore_db
  #  restart: "no"

  backend:
    build: .
    container_name: bookshop_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstore_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    build: ./bookstore-ui
    container_name: bookshop_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8081/api
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_store:
